import 'dart:ui';

import '../models/art.dart';
import 'art_specs.dart';

/// Turns the generated picture specs into paintable [ArtDef] objects.
///
/// Every picture lives in a 1000 x 1000 art space, so the whole 600 picture
/// library is pure geometry: it costs almost no memory and stays perfectly
/// sharp on every Fire tablet screen size.
///
/// The specs themselves live in `art_specs.dart`, which is generated by
/// `tools/gen/gen.py`. Nothing in this file needs to change when pictures are
/// added or redrawn.
class ArtLibrary {
  ArtLibrary._();

  /// Every shape key in the library, in category order.
  static List<String> get shapeKeys => kArtParts.keys.toList();

  /// Human readable name for a picture, e.g. `fire_engine` -> `Fire Engine`.
  static String titleFor(String key) => kArtTitles[key] ?? 'Picture';

  /// Built pictures are cached. Grid thumbnails rebuild often, and rebuilding
  /// the geometry every frame wastes CPU on low powered Fire tablets.
  static final Map<String, ArtDef> _cache = <String, ArtDef>{};

  static ArtDef build(String key) =>
      _cache.putIfAbsent(key, () => _fromParts(key));

  static ArtDef _fromParts(String key) {
    // Falling back to a known good picture means a bad or missing key can never
    // crash the coloring screen; it simply shows the star instead.
    final List<ArtPart> parts =
        kArtParts[key] ?? kArtParts['star'] ?? const <ArtPart>[];

    final List<ArtRegion> regions = <ArtRegion>[];
    final List<Path> outlines = <Path>[];

    for (final ArtPart part in parts) {
      final Path? path = _pathFor(part);
      if (path == null) continue;
      regions.add(ArtRegion(path, hint: Color(part.hint)));
      outlines.add(path);
    }

    if (regions.isEmpty) {
      // Should never happen, but a picture with nothing to tap would look
      // broken to a toddler, so draw one big friendly circle instead.
      final Path fallback =
          Path()..addOval(const Rect.fromLTRB(200, 200, 800, 800));
      return ArtDef(
        regions: <ArtRegion>[ArtRegion(fallback, hint: const Color(0xFFFFF176))],
        outlines: <Path>[fallback],
      );
    }

    return ArtDef(regions: regions, outlines: outlines);
  }

  static Path? _pathFor(ArtPart part) {
    final List<double> v = part.v;
    switch (part.kind) {
      case 0: // rounded rectangle: l, t, r, b, radius
        if (v.length < 5) return null;
        if (v[2] <= v[0] || v[3] <= v[1]) return null;
        return Path()
          ..addRRect(
            RRect.fromLTRBR(v[0], v[1], v[2], v[3], Radius.circular(v[4])),
          );
      case 1: // circle: cx, cy, radius
        if (v.length < 3 || v[2] <= 0) return null;
        return Path()
          ..addOval(Rect.fromCircle(center: Offset(v[0], v[1]), radius: v[2]));
      case 2: // oval: l, t, r, b
        if (v.length < 4) return null;
        if (v[2] <= v[0] || v[3] <= v[1]) return null;
        return Path()..addOval(Rect.fromLTRB(v[0], v[1], v[2], v[3]));
      case 3: // polygon: x0, y0, x1, y1, ...
        if (v.length < 6 || v.length.isOdd) return null;
        final Path p = Path()..moveTo(v[0], v[1]);
        for (int i = 2; i + 1 < v.length; i += 2) {
          p.lineTo(v[i], v[i + 1]);
        }
        return p..close();
      default:
        return null;
    }
  }
}
