import 'package:flutter/material.dart';

import 'art_library.dart';
import 'art_specs.dart';

class ColoringPage {
  const ColoringPage({
    required this.id,
    required this.title,
    required this.shapeKey,
    required this.categoryId,
    required this.isFree,
  });

  final String id;
  final String title;
  final String shapeKey;
  final String categoryId;
  final bool isFree;
}

class ColoringCategory {
  const ColoringCategory({
    required this.id,
    required this.title,
    required this.icon,
    required this.color,
    required this.pages,
  });

  final String id;
  final String title;
  final IconData icon;
  final Color color;
  final List<ColoringPage> pages;

  int get freeCount => pages.where((ColoringPage p) => p.isFree).length;
}

/// The full picture library.
///
/// 30 categories x 20 pages = 600 pictures, and every one of them is a
/// different drawing. The category layout, the shape keys and the free page
/// counts all come from `art_specs.dart`, which is generated by
/// `tools/gen/gen.py`, so the catalog can never drift out of sync with the
/// artwork.
///
/// Exactly 30 pages are free; the other 570 unlock with the one time purchase.
class Catalog {
  static const int pagesPerCategory = 20;

  /// Icons stay here rather than in the generated file because they are
  /// Flutter specific. Order matches [kCategorySpecs].
  static const List<IconData> _icons = <IconData>[
    Icons.directions_car_filled,
    Icons.celebration,
    Icons.toys,
    Icons.home_filled,
    Icons.beach_access,
    Icons.location_city,
    Icons.park,
    Icons.pets,
    Icons.agriculture,
    Icons.forest,
    Icons.waves,
    Icons.rocket_launch,
    Icons.egg_alt,
    Icons.restaurant,
    Icons.fire_truck,
    Icons.sports_soccer,
    Icons.music_note,
    Icons.wb_sunny,
    Icons.castle,
    Icons.local_florist,
    Icons.cake,
    Icons.checkroom,
    Icons.school,
    Icons.flutter_dash,
    Icons.cruelty_free,
    Icons.category,
    Icons.abc,
    Icons.pin,
    Icons.bedtime,
    Icons.ac_unit,
  ];

  static final List<ColoringCategory> categories = _build();

  static List<ColoringCategory> _build() {
    final List<ColoringCategory> result = <ColoringCategory>[];

    for (int c = 0; c < kCategorySpecs.length; c++) {
      final CategorySpec spec = kCategorySpecs[c];
      final List<ColoringPage> pages = <ColoringPage>[];

      for (int p = 0; p < spec.shapeKeys.length; p++) {
        final String shape = spec.shapeKeys[p];
        pages.add(
          ColoringPage(
            id: '${spec.id}_$p',
            title: ArtLibrary.titleFor(shape),
            shapeKey: shape,
            categoryId: spec.id,
            isFree: p < spec.freeCount,
          ),
        );
      }

      result.add(
        ColoringCategory(
          id: spec.id,
          title: spec.title,
          icon: c < _icons.length ? _icons[c] : Icons.image,
          color: Color(spec.color),
          pages: pages,
        ),
      );
    }
    return result;
  }

  static int get totalPages =>
      categories.fold(0, (int sum, ColoringCategory c) => sum + c.pages.length);

  static int get totalFreePages =>
      categories.fold(0, (int sum, ColoringCategory c) => sum + c.freeCount);

  static ColoringPage? pageById(String id) {
    for (final ColoringCategory c in categories) {
      for (final ColoringPage p in c.pages) {
        if (p.id == id) return p;
      }
    }
    return null;
  }
}
